name: Bump Version (Target Branch)
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"
      - run: echo "GITHUB_REF = $GITHUB_REF"
      - uses: actions/checkout@v2
      - run: echo "Bump Version (Target Branch)"
      - id: version-bump
        # We only want to bump if the branch we are merging from is not a 'Dependabot' branch
        if: ( ! contains(github.ref.name, 'dependabot'))
        uses: ./action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
